# Numpy 
(Numerical Python)

Principais recursos:
- Poderoso objeto array multidimensional.
- Funções matemáticas sofisticadas para operações com arrays, sem uso de laços for.
- Recursos de álgebra linear e geração de números aleatórios.

Documentação: https://numpy.org/doc/1.24

In [1]:
# Importando o Numpy
import numpy as np


In [2]:
# Criando um array Numpy
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
# Importando parte do pacote:
from numpy import arange

In [4]:
arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
# Criando arrays a partir de lista:
numeros = np.array([100, 988, 345, 1200])

In [6]:
numeros

array([ 100,  988,  345, 1200])

In [7]:
type(numeros)

numpy.ndarray

In [8]:
# Tipos de dados do Numpy
numeros.dtype

dtype('int64')

In [12]:
# Carregando dados externos com o Numpy:
# (NÃO ESQUEÇA DE CARREGAR O ARQUIVO TXT EXTERNO NO COLAB!!!)
teste = np.loadtxt(fname = 'test_num.txt', dtype = int)

In [11]:
teste

array([  12,   14,  200,   34,  540, 1000])

In [ ]:
teste.dtype

dtype('int64')

In [13]:
# Array de duas dimensões (Matrizes e Datasets)
dados = [
    ['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'],
    ['Paraná', 'Santa Catarina', 'Rio Grande do Sul', 'Espírito Santo'],
    ['Ceará', 'Bahia', 'Maranhão', 'Alagoas']
]

In [14]:
dados

[['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'],
 ['Paraná', 'Santa Catarina', 'Rio Grande do Sul', 'Espírito Santo'],
 ['Ceará', 'Bahia', 'Maranhão', 'Alagoas']]

In [15]:
estados = np.array(dados)

In [16]:
estados

array([['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'],
       ['Paraná', 'Santa Catarina', 'Rio Grande do Sul',
        'Espírito Santo'],
       ['Ceará', 'Bahia', 'Maranhão', 'Alagoas']], dtype='<U17')

In [17]:
type(estados)

numpy.ndarray

In [18]:
estados.shape

(3, 4)

In [19]:
# Comparando desempenho do Numpy e listas
np_array = np.arange(2000000)

In [20]:
py_list = list(range(2000000))

In [21]:
%time for _ in range(100): np_array *= 2

CPU times: user 115 ms, sys: 0 ns, total: 115 ms
Wall time: 116 ms


In [22]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 18.7 s, sys: 4.87 s, total: 23.5 s
Wall time: 23.7 s
